apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: employee-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: faizan715/employee-backend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
